name: ghgappv2
services:
  ghgapp:
    image: ihadlab-f2bnbba0fgceaff9.azurecr.io/ghgapp:v2
    container_name: ghgapp
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    environment:
      NITRO_CLUSTER_WORKERS: "8"
    restart: unless-stopped

  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
        # Give Watchtower access to the Docker API so it can manage containers
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        # Clean up old images after updating, so you don't fill disk
        WATCHTOWER_CLEANUP: "true"
        # How often to check for new images (in seconds). Example: 300 = 5 min.
        WATCHTOWER_POLL_INTERVAL: "300"
      command:
        # Limit Watchtower to only manage ghgapp (safer than updating *everything*)
        - ghgapp
        - watchtower
      restart: unless-stopped
